export type InsurerKind = "life" | "nonlife";

export type Insurer = {
  id: string;
  name: string;
  kind: InsurerKind;
  callCenter: string;
  homepageUrl: string;
  domain: string;
  termsUrl: string;
  claimsUrl: string;
};

function extractDomain(url: string) {
  const hostname = new URL(url).hostname;
  return hostname.replace(/^www\./, "");
}

function makeId(kind: InsurerKind, homepageUrl: string) {
  const domain = extractDomain(homepageUrl);
  return `${kind}-${domain.replace(/\./g, "-")}`;
}

// 생명/손해보험협회 기준 "현재 영업 중" 회원사(요청 데이터)
// - termsUrl/claimsUrl은 현재는 홈페이지 URL로 임시 세팅(추후 정식 URL로 교체 예정)
export const INSURERS: Insurer[] = [
  // 생보사 (22)
  {
    id: makeId("life", "https://www.samsunglife.com"),
    name: "삼성생명",
    kind: "life",
    callCenter: "1588-3114",
    homepageUrl: "https://www.samsunglife.com",
    domain: extractDomain("https://www.samsunglife.com"),
    termsUrl: "https://www.samsunglife.com",
    claimsUrl: "https://www.samsunglife.com",
  },
  {
    id: makeId("life", "https://www.hanwhalife.com"),
    name: "한화생명",
    kind: "life",
    callCenter: "1588-6363",
    homepageUrl: "https://www.hanwhalife.com",
    domain: extractDomain("https://www.hanwhalife.com"),
    termsUrl: "https://www.hanwhalife.com",
    claimsUrl: "https://www.hanwhalife.com",
  },
  {
    id: makeId("life", "https://www.kyobo.co.kr"),
    name: "교보생명",
    kind: "life",
    callCenter: "1588-1001",
    homepageUrl: "https://www.kyobo.co.kr",
    domain: extractDomain("https://www.kyobo.co.kr"),
    termsUrl: "https://www.kyobo.co.kr",
    claimsUrl: "https://www.kyobo.co.kr",
  },
  {
    id: makeId("life", "https://www.nhlife.co.kr"),
    name: "NH농협생명",
    kind: "life",
    callCenter: "1588-2100",
    homepageUrl: "https://www.nhlife.co.kr",
    domain: extractDomain("https://www.nhlife.co.kr"),
    termsUrl: "https://www.nhlife.co.kr",
    claimsUrl: "https://www.nhlife.co.kr",
  },
  {
    id: makeId("life", "https://www.shinhanlife.co.kr"),
    name: "신한라이프",
    kind: "life",
    callCenter: "1588-5580",
    homepageUrl: "https://www.shinhanlife.co.kr",
    domain: extractDomain("https://www.shinhanlife.co.kr"),
    termsUrl: "https://www.shinhanlife.co.kr",
    claimsUrl: "https://www.shinhanlife.co.kr",
  },
  {
    id: makeId("life", "https://www.kblifeins.com"),
    name: "KB라이프생명",
    kind: "life",
    callCenter: "1588-9999",
    homepageUrl: "https://www.kblifeins.com",
    domain: extractDomain("https://www.kblifeins.com"),
    termsUrl: "https://www.kblifeins.com",
    claimsUrl: "https://www.kblifeins.com",
  },
  {
    id: makeId("life", "https://www.miraeassetlife.co.kr"),
    name: "미래에셋생명",
    kind: "life",
    callCenter: "1588-0220",
    homepageUrl: "https://www.miraeassetlife.co.kr",
    domain: extractDomain("https://www.miraeassetlife.co.kr"),
    termsUrl: "https://www.miraeassetlife.co.kr",
    claimsUrl: "https://www.miraeassetlife.co.kr",
  },
  {
    id: makeId("life", "https://www.myangel.kr"),
    name: "동양생명",
    kind: "life",
    callCenter: "1577-1004",
    homepageUrl: "https://www.myangel.kr",
    domain: extractDomain("https://www.myangel.kr"),
    termsUrl: "https://www.myangel.kr",
    claimsUrl: "https://www.myangel.kr",
  },
  {
    id: makeId("life", "https://www.idblife.com"),
    name: "DB생명",
    kind: "life",
    callCenter: "1588-3131",
    homepageUrl: "https://www.idblife.com",
    domain: extractDomain("https://www.idblife.com"),
    termsUrl: "https://www.idblife.com",
    claimsUrl: "https://www.idblife.com",
  },
  {
    id: makeId("life", "https://www.heungkuklife.co.kr"),
    name: "흥국생명",
    kind: "life",
    callCenter: "1688-1688",
    homepageUrl: "https://www.heungkuklife.co.kr",
    domain: extractDomain("https://www.heungkuklife.co.kr"),
    termsUrl: "https://www.heungkuklife.co.kr",
    claimsUrl: "https://www.heungkuklife.co.kr",
  },
  {
    id: makeId("life", "https://www.abllife.co.kr"),
    name: "ABL생명",
    kind: "life",
    callCenter: "1588-6500",
    homepageUrl: "https://www.abllife.co.kr",
    domain: extractDomain("https://www.abllife.co.kr"),
    termsUrl: "https://www.abllife.co.kr",
    claimsUrl: "https://www.abllife.co.kr",
  },
  {
    id: makeId("life", "https://www.hanalife.co.kr"),
    name: "하나생명",
    kind: "life",
    callCenter: "1800-1110",
    homepageUrl: "https://www.hanalife.co.kr",
    domain: extractDomain("https://www.hanalife.co.kr"),
    termsUrl: "https://www.hanalife.co.kr",
    claimsUrl: "https://www.hanalife.co.kr",
  },
  {
    id: makeId("life", "https://www.dgblife.co.kr"),
    name: "DGB생명",
    kind: "life",
    callCenter: "1566-4400",
    homepageUrl: "https://www.dgblife.co.kr",
    domain: extractDomain("https://www.dgblife.co.kr"),
    termsUrl: "https://www.dgblife.co.kr",
    claimsUrl: "https://www.dgblife.co.kr",
  },
  {
    id: makeId("life", "https://www.kdblife.co.kr"),
    name: "KDB생명",
    kind: "life",
    callCenter: "1588-4040",
    homepageUrl: "https://www.kdblife.co.kr",
    domain: extractDomain("https://www.kdblife.co.kr"),
    termsUrl: "https://www.kdblife.co.kr",
    claimsUrl: "https://www.kdblife.co.kr",
  },
  {
    id: makeId("life", "https://www.metlife.co.kr"),
    name: "메트라이프생명",
    kind: "life",
    callCenter: "1588-9600",
    homepageUrl: "https://www.metlife.co.kr",
    domain: extractDomain("https://www.metlife.co.kr"),
    termsUrl: "https://www.metlife.co.kr",
    claimsUrl: "https://www.metlife.co.kr",
  },
  {
    id: makeId("life", "https://www.lina.co.kr"),
    name: "라이나생명",
    kind: "life",
    callCenter: "1588-0058",
    homepageUrl: "https://www.lina.co.kr",
    domain: extractDomain("https://www.lina.co.kr"),
    termsUrl: "https://www.lina.co.kr",
    claimsUrl: "https://www.lina.co.kr",
  },
  {
    id: makeId("life", "https://www.aia.co.kr"),
    name: "AIA생명",
    kind: "life",
    callCenter: "1588-9898",
    homepageUrl: "https://www.aia.co.kr",
    domain: extractDomain("https://www.aia.co.kr"),
    termsUrl: "https://www.aia.co.kr",
    claimsUrl: "https://www.aia.co.kr",
  },
  {
    id: makeId("life", "https://www.chubblife.co.kr"),
    name: "처브라이프생명",
    kind: "life",
    callCenter: "02-2127-2500",
    homepageUrl: "https://www.chubblife.co.kr",
    domain: extractDomain("https://www.chubblife.co.kr"),
    termsUrl: "https://www.chubblife.co.kr",
    claimsUrl: "https://www.chubblife.co.kr",
  },
  {
    id: makeId("life", "https://www.cardif.co.kr"),
    name: "BNP파리바카디프생명",
    kind: "life",
    callCenter: "02-3469-9100",
    homepageUrl: "https://www.cardif.co.kr",
    domain: extractDomain("https://www.cardif.co.kr"),
    termsUrl: "https://www.cardif.co.kr",
    claimsUrl: "https://www.cardif.co.kr",
  },
  {
    id: makeId("life", "https://www.lifeplanet.co.kr"),
    name: "교보라이프플래닛생명",
    kind: "life",
    callCenter: "1588-0114",
    homepageUrl: "https://www.lifeplanet.co.kr",
    domain: extractDomain("https://www.lifeplanet.co.kr"),
    termsUrl: "https://www.lifeplanet.co.kr",
    claimsUrl: "https://www.lifeplanet.co.kr",
  },
  {
    id: makeId("life", "https://www.imlife.co.kr"),
    name: "iM라이프",
    kind: "life",
    callCenter: "1566-2727",
    homepageUrl: "https://www.imlife.co.kr",
    domain: extractDomain("https://www.imlife.co.kr"),
    termsUrl: "https://www.imlife.co.kr",
    claimsUrl: "https://www.imlife.co.kr",
  },
  {
    id: makeId("life", "https://www.fubon-hyundai.co.kr"),
    name: "푸본현대생명",
    kind: "life",
    callCenter: "1588-1288",
    homepageUrl: "https://www.fubon-hyundai.co.kr",
    domain: extractDomain("https://www.fubon-hyundai.co.kr"),
    termsUrl: "https://www.fubon-hyundai.co.kr",
    claimsUrl: "https://www.fubon-hyundai.co.kr",
  },

  // 손보사 (16)
  {
    id: makeId("nonlife", "https://www.samsungfire.com"),
    name: "삼성화재",
    kind: "nonlife",
    callCenter: "1588-5114",
    homepageUrl: "https://www.samsungfire.com",
    domain: extractDomain("https://www.samsungfire.com"),
    termsUrl: "https://www.samsungfire.com",
    claimsUrl: "https://www.samsungfire.com",
  },
  {
    id: makeId("nonlife", "https://www.hi.co.kr"),
    name: "현대해상",
    kind: "nonlife",
    callCenter: "1588-5656",
    homepageUrl: "https://www.hi.co.kr",
    domain: extractDomain("https://www.hi.co.kr"),
    termsUrl: "https://www.hi.co.kr",
    claimsUrl: "https://www.hi.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.kbinsure.co.kr"),
    name: "KB손해보험",
    kind: "nonlife",
    callCenter: "1544-0114",
    homepageUrl: "https://www.kbinsure.co.kr",
    domain: extractDomain("https://www.kbinsure.co.kr"),
    termsUrl: "https://www.kbinsure.co.kr",
    claimsUrl: "https://www.kbinsure.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.idbins.com"),
    name: "DB손해보험",
    kind: "nonlife",
    callCenter: "1588-0100",
    homepageUrl: "https://www.idbins.com",
    domain: extractDomain("https://www.idbins.com"),
    termsUrl: "https://www.idbins.com",
    claimsUrl: "https://www.idbins.com",
  },
  {
    id: makeId("nonlife", "https://www.meritzfire.com"),
    name: "메리츠화재",
    kind: "nonlife",
    callCenter: "1566-7711",
    homepageUrl: "https://www.meritzfire.com",
    domain: extractDomain("https://www.meritzfire.com"),
    termsUrl: "https://www.meritzfire.com",
    claimsUrl: "https://www.meritzfire.com",
  },
  {
    id: makeId("nonlife", "https://www.hwgeneralins.com"),
    name: "한화손해보험",
    kind: "nonlife",
    callCenter: "1566-8000",
    homepageUrl: "https://www.hwgeneralins.com",
    domain: extractDomain("https://www.hwgeneralins.com"),
    termsUrl: "https://www.hwgeneralins.com",
    claimsUrl: "https://www.hwgeneralins.com",
  },
  {
    id: makeId("nonlife", "https://www.lotteins.co.kr"),
    name: "롯데손해보험",
    kind: "nonlife",
    callCenter: "1588-3344",
    homepageUrl: "https://www.lotteins.co.kr",
    domain: extractDomain("https://www.lotteins.co.kr"),
    termsUrl: "https://www.lotteins.co.kr",
    claimsUrl: "https://www.lotteins.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.heungkukfire.co.kr"),
    name: "흥국화재",
    kind: "nonlife",
    callCenter: "1688-1688",
    homepageUrl: "https://www.heungkukfire.co.kr",
    domain: extractDomain("https://www.heungkukfire.co.kr"),
    termsUrl: "https://www.heungkukfire.co.kr",
    claimsUrl: "https://www.heungkukfire.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.nhfire.co.kr"),
    name: "NH농협손해보험",
    kind: "nonlife",
    callCenter: "1644-9000",
    homepageUrl: "https://www.nhfire.co.kr",
    domain: extractDomain("https://www.nhfire.co.kr"),
    termsUrl: "https://www.nhfire.co.kr",
    claimsUrl: "https://www.nhfire.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.educar.co.kr"),
    name: "하나손해보험",
    kind: "nonlife",
    callCenter: "1566-3000",
    homepageUrl: "https://www.educar.co.kr",
    domain: extractDomain("https://www.educar.co.kr"),
    termsUrl: "https://www.educar.co.kr",
    claimsUrl: "https://www.educar.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.axa.co.kr"),
    name: "AXA손해보험",
    kind: "nonlife",
    callCenter: "1566-1566",
    homepageUrl: "https://www.axa.co.kr",
    domain: extractDomain("https://www.axa.co.kr"),
    termsUrl: "https://www.axa.co.kr",
    claimsUrl: "https://www.axa.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.aig.co.kr"),
    name: "AIG손해보험",
    kind: "nonlife",
    callCenter: "1544-2792",
    homepageUrl: "https://www.aig.co.kr",
    domain: extractDomain("https://www.aig.co.kr"),
    termsUrl: "https://www.aig.co.kr",
    claimsUrl: "https://www.aig.co.kr",
  },
  {
    id: makeId(
      "nonlife",
      "https://kakaopayinscorp.co.kr"
    ),
    name: "카카오페이손해보험",
    kind: "nonlife",
    callCenter: "1544-0022",
    homepageUrl: "https://kakaopayinscorp.co.kr",
    domain: extractDomain("https://kakaopayinscorp.co.kr"),
    termsUrl: "https://kakaopayinscorp.co.kr",
    claimsUrl: "https://kakaopayinscorp.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.shinhanez.co.kr"),
    name: "신한EZ손해보험",
    kind: "nonlife",
    callCenter: "1544-2580",
    homepageUrl: "https://www.shinhanez.co.kr",
    domain: extractDomain("https://www.shinhanez.co.kr"),
    termsUrl: "https://www.shinhanez.co.kr",
    claimsUrl: "https://www.shinhanez.co.kr",
  },
  {
    id: makeId("nonlife", "https://www.mggeneralins.com"),
    name: "MG손해보험",
    kind: "nonlife",
    callCenter: "1588-5959",
    homepageUrl: "https://www.mggeneralins.com",
    domain: extractDomain("https://www.mggeneralins.com"),
    termsUrl: "https://www.mggeneralins.com",
    claimsUrl: "https://www.mggeneralins.com",
  },
  {
    id: makeId("nonlife", "https://www.sgic.co.kr"),
    name: "서울보증보험",
    kind: "nonlife",
    callCenter: "1670-7000",
    homepageUrl: "https://www.sgic.co.kr",
    domain: extractDomain("https://www.sgic.co.kr"),
    termsUrl: "https://www.sgic.co.kr",
    claimsUrl: "https://www.sgic.co.kr",
  },
];

